#!/usr/bin/python3

#    Copyright (c) 2020 Vittorio Folino 
#
#    This file is part of lsensors.
# 
#    lsensors is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    lsensors is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with lsensors.  If not, see <http://www.gnu.org/licenses/>.

from lib import settings
from lib import sens
import os
import sys

absRoot =  os.path.dirname(os.path.abspath(__file__))
helpMsg = os.path.join(absRoot, 'etc/help.txt')

def showHlp():
    with open(helpMsg, 'r') as hlp:
        print(hlp.read())

def main():
    #getting initial settings, might be defaults
    sets = settings.Settings(absRoot)
    setted = sets.getSettings()
    #Sensors class updates the settings giving back
    #the list of sensors if not found in defaults
    sensors = sens.Sensors(absRoot, setted)
    setted = sensors.settings
    #updating and saving
    sets.update(setted)
    sets.save()

    keyDictionary = {
        #flags to log on file in working dir
        '-l' : sensors.logAll,
        '--log' : sensors.logAll,
        #flags to print on print on console
        '-p' : sensors.printAll,
        '--print' : sensors.printAll,
        #flags to print help message
        '-h' : showHlp,
        '--help' : showHlp
    }

    if len(sys.argv) == 2:
        keyDictionary[sys.argv[1]]()
    else:
        showHlp()

if __name__ == "__main__":
    main()
